import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleLogin, GoogleOAuthProvider } from '@react-oauth/google';
import Link from "next/link";
import { useState } from "react";
import { JwtPayload, jwtDecode } from "jwt-decode";
import Navbar from "./Navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <head>
        <script src="https://accounts.google.com/gsi/client" async defer></script>
      </head>
      <GoogleOAuthProvider clientId="30623345891-rajc4i6lpf9sb36pt49bllt82aqlijbe.apps.googleusercontent.com">
        <body className={inter.className}>
          <Navbar />
          {children}
        </body>
      </GoogleOAuthProvider>
    </html>
  );
}
